# Generated by Django 3.1.6 on 2021-02-06 17:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=10000)),
                ('url', models.CharField(max_length=200)),
                ('thumbnail', models.CharField(max_length=200)),
                ('lang', models.CharField(max_length=200)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='VideosTopics',
            fields=[
                ('topic_id', models.AutoField(primary_key=True, serialize=False)),
                ('video_id', models.ManyToManyField(to='videos.Videos')),
            ],
        ),
    ]
